# Generated by Django 3.2.4 on 2021-07-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='colaboradores',
            fields=[
                ('rut', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='rut: ')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='img/')),
                ('nombre', models.CharField(max_length=20, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=20, verbose_name='apellido')),
                ('telefono', models.IntegerField(verbose_name='telefono')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('correo_electronico', models.CharField(max_length=40, verbose_name='correo_electronico')),
                ('pais', models.CharField(max_length=15, verbose_name='pais')),
                ('contrasena', models.CharField(max_length=20, verbose_name='contrasena')),
            ],
        ),
    ]
