# Generated by Django 3.2.4 on 2021-07-03 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradores',
            name='apellido',
            field=models.CharField(max_length=20, verbose_name='apellidos'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='contrasena',
            field=models.CharField(max_length=20, verbose_name='contraseña'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='nombres'),
        ),
        migrations.AlterField(
            model_name='colaboradores',
            name='rut',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='rut '),
        ),
    ]
